import pandas as pd
import numpy as np
import tensorflow as tf
import cv2
import os
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
from keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# ==========================================
# 1. LOAD AND PREPARE THE DATA
# ==========================================
print("Loading dataset...")
df = pd.read_csv("physiovision_bicep_curls.csv")

videos = df.groupby("video_id")

X_data = []
y_data = []

TARGET_FRAMES = 40
NUM_FEATURES = 99

def normalize_curl_data(frames_array):
    data = frames_array.reshape(-1, 33, 3)
    mid_hip = (data[:, 23:24, :] + data[:, 24:25, :]) / 2.0
    data = data - mid_hip
    mid_sh = (data[:, 11:12, :] + data[:, 12:13, :]) / 2.0
    torso_length = np.linalg.norm(mid_sh - mid_hip, axis=2, keepdims=True)
    data = data / np.maximum(torso_length, 0.0001)
    return data.reshape(-1, 99)

for video_id, group in videos:
    label = group["class_label"].iloc[0]
    coords = group.iloc[:, 3:].values

    warped_coords = cv2.resize(np.float32(coords), (NUM_FEATURES, TARGET_FRAMES), interpolation=cv2.INTER_LINEAR)

    normalized_coords = normalize_curl_data(warped_coords)

    X_data.append(warped_coords)
    y_data.append(label)

X = np.array(X_data)
y_raw = np.array(y_data)

print(f"Total sequences processed: {len(X)}")

# ==========================================
# 2. ENCODE LABELS
# ==========================================
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y_raw)

print("\nClass Mapping generated by encoder:")
class_mapping = dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))
for name, num in class_mapping.items():
    print(f"  {num}: {name}")

y = tf.keras.utils.to_categorical(y_encoded)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ==========================================
# 3. BUILD THE NEURAL NETWORK (LSTM)
# ==========================================
print("\nBuilding Model Architecture...")

# FIXED ARCHITECTURE: No separate Input layer, no batch_shape bugs.
model = Sequential([
    LSTM(64, input_shape=(TARGET_FRAMES, NUM_FEATURES), return_sequences=True),
    Dropout(0.2),
    LSTM(32, return_sequences=False),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(len(class_mapping), activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# ==========================================
# 4. TRAIN THE MODEL
# ==========================================
print("\nCommencing Training Phase...")
stopper = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1)

history = model.fit(
    X_train, y_train,
    epochs=150,
    batch_size=16,
    validation_data=(X_test, y_test),
    callbacks=[stopper],
    verbose=1
)

# ==========================================
# 5. SAVE AND DEPLOY
# ==========================================
loss, accuracy = model.evaluate(X_test, y_test)
print(f"\nFinal Test Accuracy: {accuracy * 100:.2f}%")

# Saving natively as .keras directly into the current directory
model_filename = "bicep_curl_robust.keras"
model.save(model_filename)

# Verification check to make sure it didn't zero-out
file_size = os.path.getsize(model_filename)
print(f"\nSUCCESS! Brain saved as '{model_filename}'")
print(f"File Size Verification: {file_size / 1024:.2f} KB")